sudo: required

language: go

go:
  - 1.7
  - tip

go_import_path: github.com/ripplxyz/rippl

before_install:
  - sudo add-apt-repository -y ppa:masterminds/glide
  - sudo apt-get -y update
  - sudo apt-get -y install glide

install: make deps

script: make travis